export const LOAD_BOARDS_SUCCESS = "LOAD_BOARDS_SUCCESS"
export const SET_CARDVIEW_VISIBLE = "SET_CARDVIEW_VISIBLE"
export const SET_CARDVIEW_OPENED_ID = "SET_CARDVIEW_OPENED_ID"
export const RECEIVE_CARD = "RECEIVE_CARD"
export const REQUEST_CARD = "REQUEST_CARD"

export const REQUEST_ALL_BOARDS = "REQUEST_ALL_BOARDS"
export const RECEIVE_ALL_BOARDS = "RECEIVE_ALL_BOARDS"
